// A CLI tool and library for producing "prelude" files that lift declarations out of inner source packages.
package prude

// Autogenerated by prude.


import "lib"

// Formats and writes a list of prelude entries to a string, suitable for use in an odin file.
write_entries :: lib.write_entries

// Formats and writes a list of imports to a string, suitable for use in an odin file.
write_source_list :: lib.write_source_list

// Formats and writes to a string buffer an odin compliant file describing a prelude.
write_package :: lib.write_package

// Zero-initializes prelude. Allocates dynamic arrays for the entries and sources using provided allocator.
// You should also set `name` and `path` after calling this.
prelude_init :: lib.prelude_init

// Allocates prelude on the heap and initializes it.
prelude_make :: lib.prelude_make

// Frees prelude its contained dynamic arrays.
prelude_destroy :: lib.prelude_destroy

// Parses a string into an odin-compliant docstring, ideally to be placed into a `Prelude`.
//
// ## Allocations
// The returned string is allocated with `allocator` must be freed by the caller.
// Additionally the internal string builder is allocated and freed with `context.temp_allocator`
parse_docs :: lib.parse_docs

// Parses docs as according to `parse_docs` but from a file handle.
//
// ## Allocations
// This is a wrapper over `parse_docs` and as such also returns a string that must be freed.
// It allocates in all the same ways.
// If logging allows, it also uses `allocator` to allocate the file stats for debugging.
parse_docs_from_file :: lib.parse_docs_from_file

// Writes prelude to file specified in `prelude.path`.
output_to_file :: lib.output_to_file

// Writes prelude output to string.
//
// ## Allocations
// This allocates a strings.Builder using the provided allocator.
// The returned string needs to be freed by the caller.
output_to_string :: lib.output_to_string

// Adds source to prelude using a specified path to directory.
// `path` should be a directory.
add_source :: lib.add_source

add_file :: lib.add_file

// Errors than can occur during scanning and generation.
Error :: lib.Error

// An error that occured during the scanning phase.
Scan_Error :: lib.Scan_Error

// A collection of entries and sources associated with a package name. Used to generate a source code file.
// Be sure to initialize with `prelude_init` (or allocate with `prelude_make`) and free with `prelude_destroy`.
// Before using, set `name` and `path`.
Prelude :: lib.Prelude

// An exported entry to be placed in the prelude.
Entry :: lib.Entry

// A description of a path to a package and its name as referenced in code.
Source :: lib.Source

