package core

import "core:log"
import "core:strings"

// Formats and writes a list of prelude entries to a string, suitable for use in an odin file.
write_entries :: proc(
	buffer : ^strings.Builder,
	entries : []Entry,
) -> (
	bytes_written : int,
) {
	for entry in entries {
		old_bytes := bytes_written
		bytes_written += strings.write_string(buffer, entry.documentation)
		bytes_written += strings.write_string(buffer, entry.name)
		bytes_written += strings.write_string(buffer, " :: ")
		bytes_written += strings.write_string(buffer, entry.source)
		bytes_written += strings.write_string(buffer, "\n\n")
		log.debugf(
			"Wrote %v bytes for entry: '%v'",
			bytes_written - old_bytes,
			entry.name,
		)
	}
	return bytes_written
}

// Formats and writes a list of imports to a string, suitable for use in an odin file.
write_source_list :: proc(
	buffer : ^strings.Builder,
	sources : []Source,
) -> (
	bytes_written : int,
) {
	for source in sources {
		old_bytes := bytes_written
		is_default := strings.has_suffix(source.path, source.name)
		bytes_written += strings.write_string(buffer, "import ")
		if !is_default {
			bytes_written += strings.write_string(buffer, source.name)
			bytes_written += strings.write_byte(buffer, ' ')
		}
		bytes_written += strings.write_quoted_string(buffer, source.path)
		bytes_written += strings.write_string(buffer, "\n")

		log.debugf(
			"Wrote %v bytes for source import: %v",
			bytes_written - old_bytes,
			source,
		)
	}
	return bytes_written
}

// Formats and writes to a string buffer an odin compliant file describing a prelude.
write_package :: proc(
	buffer : ^strings.Builder,
	prelude : ^Prelude,
) -> (
	bytes_written : int,
) {
	bytes_written += strings.write_string(buffer, prelude.docs)
	bytes_written += strings.write_string(buffer, "package ")
	bytes_written += strings.write_string(buffer, prelude.name)
	bytes_written += strings.write_string(
		buffer,
		"\n\n// Autogenerated by prude.\n\n\n",
	)
	bytes_written += write_source_list(buffer, prelude.sources[:])
	bytes_written += strings.write_byte(buffer, '\n')
	bytes_written += write_entries(buffer, prelude.entries[:])
	log.debugf("Wrote %v bytes for package", bytes_written)
	return bytes_written
}
